In [37]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [38]:
import numpy as np
from particle import literals as lp
import DarkNews as dn
from DarkNews import model
from DarkNews import const
from DarkNews import GenLauncher

In [106]:
proton = dn.detector.NuclearTarget("H1")

# model
self   = dn.model.ThreePortalModel(name='NC_test', m4 = 0.1, m5 = 0.2, UD4=1/np.sqrt(2), UD5=1/np.sqrt(2), Umu4=1e-3, Ue4=1e-3,  Umu5=1e-2, Ue5=1e-3, epsilon=1e-2, gD=2)

/Users/matheushostert/Repos/DarkNews-generator/src/DarkNews/model.py:591: RuntimeWarning: invalid value encountered in sqrt
  # Z coupling of between LOW-ENERGY flavor states and the mass eigenstates


In [108]:
Ulep_dark_only = np.diag(6*[0])
Ulep_dark_only[self.inds_dark,self.inds_dark] = self.Ulep[self.inds_dark,self.inds_dark]

DIJ = self.gD*(Ulep_dark_only - np.dot(self.Ulep[:,3:], self.D_dark[3:]))
DIJ[3:, 3:] = self.d_ij[3:, 3:]

print(DIJ[3,4])
print(self.d_ij[3,4])

0.9999999999958912
0.9999999999958912


In [105]:
self.d_ij[3:, 3:]

array([[1., 1., 0.],
       [1., 1., 0.],
       [0., 0., 0.]])

In [10]:
self.le_state_norms

array([0.9999995 , 0.99498744, 1.        , 0.        , 0.        ,
       0.        ])

In [6]:
np.sqrt(1 - ((np.dot(self.Ulep.conjugate().T, self.Ulep))).sum())

/var/folders/my/7j7cn6f92_z66yvbb11lgt2r0000gn/T/ipykernel_21827/1574190856.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(1 - ((np.dot(self.Ulep.conjugate().T, self.Ulep))).sum())


nan

In [205]:
self.d_aj

array([[9.99999626e-01, 9.99999990e-01, 1.00000000e+00, 9.99990000e-01,
        1.00000000e+00, 1.00000000e+00],
       [9.99999990e-01, 9.99998626e-01, 1.00000000e+00, 9.99000000e-01,
        1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 9.99999626e-01, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00],
       [9.99990000e-01, 9.99000000e-01, 1.00000000e+00, 3.73542317e-13,
        1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00]])

In [169]:
self.c_aj

array([[ 3.75820937e-01, -3.75820937e-09,  0.00000000e+00,
         3.70455508e-06,  0.00000000e+00,  0.00000000e+00],
       [-3.75820937e-09,  3.75820561e-01,  0.00000000e+00,
         3.70455508e-04,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  3.75820937e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         3.70455508e-01,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.75820937e-01,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  3.75820937e-01]])

In [118]:
print(self.Ulep)
print(self.c_ij)
print(f'{np.diag(6*[1]) - np.dot(self.Ulep[:,3:], self.c_ij[3:,:])}')

[[1.    0.    0.    0.    0.    0.   ]
 [0.    1.    0.    0.001 0.    0.   ]
 [0.    0.    1.    0.    0.    0.   ]
 [0.    0.001 0.    1.    0.    0.   ]
 [0.    0.    0.    0.    1.    0.   ]
 [0.    0.    0.    0.    0.    1.   ]]
[[0.37045588 0.         0.         0.         0.         0.        ]
 [0.         0.37045588 0.         0.00037582 0.         0.        ]
 [0.         0.         0.37045588 0.         0.         0.        ]
 [0.         0.00037582 0.         0.00536543 0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  9.99999624e-01  0.00000000e+00 -5.36542886e-06
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -3.75820937e-04  0.00000000e+

In [68]:
self.c_aj = (
    # Z coupling to J_NC^[e, mu, tau]
    self._weak_vertex * np.dot(np.diag(1 - self.UahUah_mass_summed), self.Uactive_heavy) * self._g_weak_correction\
    # Z coupling to J_dark^[d, ..., d^{n_dark_flavors}]
    + np.dot(np.diag(-self.UahUDh_mass_summed), self.UD_heavy) * self._gschi 
)

# Z' vertices d_ij (n x n) where ij are mass eigenstate indices 
self.d_ij = self._weak_vertex * self.C_weak * self._g_dark_correction + self.D_dark * self.gD

# d_aj (3 x 3)
#   columns: 0 - e, 1 - mu, 2 -tau 
#   rows: 0 - N4, 1 - N5, 2 - N6
self.d_aj = (
    # Z' coupling to J_NC^[e, mu, tau]
    self._weak_vertex * np.dot(np.diag(1 - self.UahUah_mass_summed), self.Uactive_heavy) * self._g_dark_correction\
    # Z' coupling to J_dark^[d, ..., d^{n_dark_flavors}, s, s2, s, ...]
    + np.dot(np.diag(-self.UahUDh_mass_summed), self.UD_heavy) * self.gD
)

# make it 3 x n_nus
self.c_aj_new = np.hstack((np.diag([1, 1, 1]), self.c_aj))
self.d_aj_new = np.hstack((np.diag([1, 1, 1]), self.d_aj))

In [71]:
self.d_aj

array([[-0.001,  0.   ,  0.   ],
       [-0.001,  0.   ,  0.   ],
       [-0.001,  0.   ,  0.   ]])

In [19]:
np.dot(np.diag(-model_test.UahUDh_mass_summed), model_test.UD_heavy)

array([[-0.001,  0.   ,  0.   ]])

In [11]:
MODEL_KWARGS = {'HNLtype': 'dirac', 'UD4': 1.0, 'alphaD': 0.25, 'Umu4': np.sqrt(9e-7), 'epsilon': np.sqrt(2e-10/const.alphaQED)}

gen = GenLauncher(mzprime=0.2, m4=0.4, decay_product='mu+mu-', neval=1000, experiment="miniboone_fhc", loglevel='DEBUG', seed=42, **MODEL_KWARGS)
df_heavy = gen.run()


---------------------------------------------------------
   ______           _        _   _                     
   |  _  \         | |      | \ | |                    
   | | | |__ _ _ __| | __   |  \| | _____      _____   
   | | | / _  | ___| |/ /   | .   |/ _ \ \ /\ / / __|  
   | |/ / (_| | |  |   <    | |\  |  __/\ V  V /\__ \  
   |___/ \__,_|_|  |_|\_\   \_| \_/\___| \_/\_/ |___/  

---------------------------------------------------------
Model:
	1 dirac heavy neutrino(s).

---------------------------------------------------------
Experiment:
	MiniBooNE_FHC
	fluxfile loaded: MiniBooNE_FHC.dat
	POT: 1.875e+21
	nuclear targets: ['C12', 'H1']
	fiducial mass: [701.1428571428571, 116.85714285714286] tonnes

Creating instances of MC cases:
Created an MC instance of nu(mu) C12 --> N4  C12 --> nu_light mu+ mu- C12.
Created an MC instance of nu(mu) proton_in_C12 --> N4  proton_in_C12 --> nu_light mu+ mu- proton_in_C12.
Created an MC instance of nu(mu) proton_in_H1 --> N4  proton_in_H1

In [32]:
MODEL_KWARGS = {"HNLtype": "dirac", "UD4": 1.0, "alphaD": 0.25, "Umu4": np.sqrt(9e-7), 
                "epsilon": np.sqrt(2e-10 / const.alphaQED)}

GENERIC_MODEL_KWARGS = {"HNLtype": "dirac", "deV": 1, "duV": 1, "ddV": 1,
                    "d_mu4": 1, "d_mu5": 1, "d_mu6": 1,
                    "d_45": 1, "d_56": 1, "d_46": 1}

# generate a specific set of events to be tested in a session
def SM_gen():
    gen = GenLauncher(gD=0.0, Umu4=1e-3, epsilon=0.0, m4=0.01, loglevel='ERROR', neval=1000, seed=42)
    return gen.run()

def light_DP_gen_all_outputs():
    gen = GenLauncher(
        mzprime=0.03,
        m4=0.420,
        neval=1000,
        experiment="miniboone_fhc",
        loglevel="ERROR",
        seed=42,
        parquet=True,
        numpy=True,
        hepevt=True,
        hepevt_legacy=True,
        hepmc2=True,
        hepmc3=True,
        **MODEL_KWARGS
    )
    return gen.run()

def generic_model_gen():

    gen = GenLauncher(
        mzprime=0.03,
        m4=0.100,
        m5=0.200,
        m6=0.300,
        neval=1000,
        experiment="miniboone_fhc",
        loglevel="ERROR",
        seed=42,
        parquet=True,
        numpy=True,
        hepevt=True,
        hepevt_legacy=True,
        hepmc2=True,
        hepmc3=True,
        hep_unweight=True,
        hep_unweight_events=100,
        **GENERIC_MODEL_KWARGS
    )
    return gen.run()

def light_DP_gen_all_outputs_sparse():

    gen = GenLauncher(
        mzprime=0.03,
        m4=0.425,
        neval=1000,
        experiment="miniboone_fhc",
        loglevel="ERROR",
        seed=42,
        parquet=True,
        numpy=True,
        hepevt=True,
        hepevt_legacy=True,
        hepmc2=True,
        hepmc3=True,
        sparse=True,
        print_to_float32=True,
        **MODEL_KWARGS
    )
    return gen.run()

def gen_simplest_benchmarks():

    gen = GenLauncher(mzprime=0.03, m4=0.420, neval=1000, experiment="miniboone_fhc", loglevel="ERROR", seed=42, **MODEL_KWARGS)
    df_light = gen.run()

    gen = GenLauncher(mzprime=1.25, m4=0.150, neval=1000, experiment="miniboone_fhc", loglevel="ERROR", seed=42, **MODEL_KWARGS)
    df_heavy = gen.run()

    gen = GenLauncher(mu_tr_mu4=1e-6, m4=0.150, epsilon=0.0, gD=0.0, Umu4=0.0, neval=1000, experiment="miniboone_fhc", loglevel="ERROR", seed=42)
    df_TMM = gen.run()

    return df_light, df_heavy, df_TMM

def gen_other_final_states():

    gen = GenLauncher(mzprime=0.3, m4=0.5, decay_product="mu+mu-", neval=1000, experiment="miniboone_fhc", loglevel="ERROR", seed=42, **MODEL_KWARGS)
    df_light = gen.run()

    gen = GenLauncher(mzprime=1.25, m4=0.5, decay_product="mu+mu-", neval=1000, experiment="miniboone_fhc", loglevel="ERROR", seed=42, **MODEL_KWARGS)
    df_heavy = gen.run()

    gen = GenLauncher(
        mu_tr_mu4=1e-6,
        m4=0.5,
        epsilon=0.0,
        gD=0.0,
        decay_product="mu+mu-",
        Umu4=0.0,
        neval=1000,
        HNLtype="dirac",
        experiment="miniboone_fhc",
        loglevel="ERROR",
        seed=42,
    )
    df_TMM_mumu = gen.run()

    gen = GenLauncher(
        mu_tr_mu4=1e-6,
        m4=0.5,
        epsilon=0.0,
        gD=0.0,
        decay_product="photon",
        Umu4=0.0,
        neval=1000,
        HNLtype="dirac",
        experiment="miniboone_fhc",
        loglevel="ERROR",
        seed=42,
    )
    df_TMM_photon = gen.run()

    return df_light, df_heavy, df_TMM_mumu, df_TMM_photon


In [33]:
df = SM_gen()
df.w_event_rate.sum()

0.0383833061138531

In [35]:
df_light,df_heavy,df_TMM = gen_simplest_benchmarks()

print(df_light.w_event_rate.sum())
print(df_heavy.w_event_rate.sum())
print(df_TMM.w_event_rate.sum())

13349.332011155739
5.502976676512979
52283.95934429322


In [36]:
df_light, df_heavy, df_TMM_mumu, df_TMM_photon = gen_other_final_states()

print(df_light.w_event_rate.sum())
print(df_heavy.w_event_rate.sum())
print(df_TMM_mumu.w_event_rate.sum())
print(df_TMM_photon.w_event_rate.sum())

201.95690347250735
2.3240714690039566
3426.3242951080792
3446.7854182166047


In [4]:
bsm_model_1 = dn.model.create_3portal_HNL_model(mzprime=1.25, m4=0.1, m5=0.150, Umu4=1e-3, Umu5=2e-3, UD4=0.2, UD5=0.2, epsilon=1e-4)
# bsm_model_2 = dn.model.create_generic_HNL_model()

AttributeError: 'ThreePortalModel' object has no attribute 'HNLtype'

In [107]:
x = bsm_model_1.d_ij
print(np.array2string(x, formatter={'float_kind':lambda x: "%.1E" % x if x !=0 else "0.00000"}))

[[-3.7E-08 0.00000 0.00000 0.00000 0.00000 0.00000]
 [0.00000 9.6E-07 0.00000 2.0E-04 2.0E-04 0.00000]
 [0.00000 0.00000 -3.7E-08 0.00000 0.00000 0.00000]
 [0.00000 2.0E-04 0.00000 4.0E-02 4.0E-02 0.00000]
 [0.00000 2.0E-04 0.00000 4.0E-02 4.0E-02 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]]


In [108]:
print(np.sqrt(np.sum(np.abs(bsm_model_1.d_aj[const.inds_active,3])**2)))
print(np.sqrt(np.sum(np.abs(bsm_model_1.d_ij[const.inds_active,3])**2)))

0.00020784611846974275
0.00019999996265424277


In [109]:
# x = np.vstack((bsm_model_1.d_aj,bsm_model_1.d_ij[3:]))
x = bsm_model_1.d_aj
print(np.array2string(x, formatter={'float_kind':lambda x: "%.1E" % x if x !=0 else "0.00000"}))

[[1.0E+00 0.00000 0.00000 -1.2E-04 -1.2E-04 0.00000]
 [0.00000 1.0E+00 0.00000 -1.2E-04 -1.2E-04 0.00000]
 [0.00000 0.00000 1.0E+00 -1.2E-04 -1.2E-04 0.00000]
 [0.00000 2.0E-04 0.00000 4.0E-02 4.0E-02 0.00000]
 [0.00000 2.0E-04 0.00000 4.0E-02 4.0E-02 0.00000]
 [0.00000 0.00000 0.00000 0.00000 0.00000 0.00000]]


In [116]:
decay_1=dn.processes.FermionDileptonDecay(dn.pdg.neutrino4, dn.pdg.nulight, lp.e_minus, lp.e_plus, bsm_model_1)
ups_case=dn.processes.UpscatteringProcess(dn.pdg.numu, bsm_model_1.neutrino4, dn.nuclear_tools.NuclearTarget("C12"), 'coherent', bsm_model_1, 'conserving')
# decay_2=dn.model.FermionDileptonDecay(dn.pdg.neutrino4, dn.pdg.nulight, lp.e_minus, lp.e_plus, bsm_model_2)

In [117]:
const.gweak/2.0/const.cw*np.abs((1.0-4.0*const.s2w)*self.target.Z-self.target.N)

NameError: name 'self' is not defined

In [124]:
ups_case.Chad/(bsm_model_1.cVproton*6 + bsm_model_1.cVneutron*6)

-1.9999999771191013

In [119]:
ups_case.Vhad/(bsm_model_1.dVproton*6 + bsm_model_1.dVneutron*6)

0.98127287696488

In [110]:
bsm_model = dn.model.create_HNL_model(mzprime=0.1, 
                                            m5=0.150, 
                                            m4 = 0.01, 
                                            epsilon=0.0, 
                                            theta=1e-4, 
                                            s_mu4=1e-3
                                        )

AttributeError: module 'DarkNews.model' has no attribute 'create_HNL_model'